version: '3.4'
services:
  redismod:
    image: redismod
    build: redis/
    ports:
      - 6379:6379
    volumes:
      - type: volume
        source: redis_data
        target: /Users/wittawas/Working/ignitry/tools/docker/redis/data
        volume:
          nocopy: true


volumes:
  redis_data:
    external: false
