services:
  swagger-ui:
    image: docker.swagger.io/swaggerapi/swagger-ui
    ports:
      - "80:8080"
    environment:
      - SWAGGER_JSON=/foo/swagger.json
    volumes:
      - ./swagger.json:/foo/swagger.json
      - ./bar:/foo
